# Generated by Django 5.1.4 on 2024-12-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavators_detector', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
